version: '3.7'

services:

  #Start Mongo db
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"

  hospital-platform:
    image: ismailharik/hospital-platform
    container_name: hospital-platform
    environment:
      - MONGO_HOST=mongodb
      - MONGO_PORT=27017
      - MONGO_DATABASE=hospital-db
    ports:
      - "8081:8081"
    volumes:
      - "./mongo/db:/data/db"